# Generated by Django 5.1.4 on 2024-12-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videolecture",
            name="semester",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videolecture",
            name="year",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videonote",
            name="semester",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videonote",
            name="year",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
