# Generated by Django 5.1.4 on 2024-12-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_videolecture_semester_videolecture_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videolecture",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="videolecture",
            name="year",
        ),
        migrations.RemoveField(
            model_name="videonote",
            name="notes_url",
        ),
        migrations.RemoveField(
            model_name="videonote",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="videonote",
            name="year",
        ),
        migrations.AddField(
            model_name="videonote",
            name="notes_image",
            field=models.ImageField(default=1, upload_to="notes_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videonote",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_notes",
                to="academy.branch",
            ),
        ),
    ]
