# Generated by Django 5.1.4 on 2024-12-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_remove_videonote_branch_videonote_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videonote",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_notes",
                to="academy.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videonote",
            name="notes_image",
            field=models.ImageField(default=1, upload_to="notes_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videonote",
            name="semester",
            field=models.IntegerField(choices=[(1, "Semester 1"), (2, "Semester 2")]),
        ),
        migrations.AlterField(
            model_name="videonote",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="videonote",
            name="video_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
