# Generated by Django 5.1.4 on 2024-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_videonote_branch_alter_videonote_notes_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videonote",
            name="semester",
            field=models.IntegerField(
                choices=[
                    (1, "Semester 1"),
                    (2, "Semester 2"),
                    (3, "Semester 3"),
                    (4, "Semester 4"),
                    (5, "Semester 5"),
                    (6, "Semester 6"),
                    (7, "Semester 7"),
                    (8, "Semester 8"),
                ]
            ),
        ),
    ]
