# Generated by Django 5.1.4 on 2024-12-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_alter_videonote_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="notes_images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="videonote",
            name="notes_image",
        ),
        migrations.AddField(
            model_name="videonote",
            name="notes_images",
            field=models.ManyToManyField(
                related_name="video_notes", to="academy.notesimage"
            ),
        ),
    ]
