# Generated by Django 5.1.4 on 2024-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_notesimage_remove_videonote_notes_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videonote",
            name="notes_images",
        ),
        migrations.AddField(
            model_name="videonote",
            name="notes_image",
            field=models.ImageField(default=1, upload_to="notes_images/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="NotesImage",
        ),
    ]
